import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Form from '../components/form/Form'

import { useConnect } from 'wagmi'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import { isValidCookie } from '../requests'
import DefaultErrorPage from 'next/error'

export default function Home() {

  const { query } = useRouter()

  const [isSessionCookieValid, setIsSessionCookieValid] = useState(false)
  const [isLoading, setIsLoading] = useState(true)
  
  useEffect(() => {
      isValidCookie(query.session).then((res) => {
        const isValid = res.data.isValid
        setIsSessionCookieValid(isValid)
        setIsLoading(false)
      }) 
  })

  const renderComponent = () => {
    if(isSessionCookieValid && !isLoading) {
      return <Form />
    } else if(isLoading) {
      return <div></div>
    } else {
      return <DefaultErrorPage statusCode={404} />
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>yWhales</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {renderComponent()}
      </main>
    </div>
  )
}
